vich_uploader:
    db_driver: orm

    mappings:
       itineraire_image:
           uri_prefix: /images/itineraire
           upload_destination: '%kernel.project_dir%/public/images/itineraire'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
