vich_uploader:
    db_driver: orm

    mappings:
        itineraire_image:
           uri_prefix: /images/itineraire
           upload_destination: '%kernel.project_dir%/public/images/itineraire'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

    # mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
